name: 'IMMEDIATEBOND '
favicon: null
layout_spectrum: 0
typography_spectrum: 1
title: THIRST TO CONNECT
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FEFEFE'
    - '#282828'
    - '#8E8A8B'
    - '#C1BEBF'
    - '#686465'
  brandStrength: 0.875
  lightness: 0.4375
  saturation: 0.75
  rhythmicContrast: 1
purpose: []
